
export enum MEMBER_TYPE_ENUM {
    ADMIN = 'Admin',
    AGENT = 'Agent',
    APPRAISER = 'Appraiser',
    ATTORNEY = 'Attorney',
    BROKER = 'Broker',
    BUYER = 'Buyer',
    CONTRACTOR = 'Contractor',
    FRIEND_FAMILY = 'Friend/Family',
    INSPECTOR = 'Inspector',
    LENDER = 'Lender',
    RENTER = 'Renter',
    SELLER = 'Seller',
    TITLE_AGENT = 'Title Agent',
    TRANSACTION_COORDINATOR = 'Transaction Coordinator',
    OTHER = 'Other'
  }
  
  export enum USER_ROLE {
    CREATOR = 'creator',
    ADMIN = MEMBER_TYPE_ENUM.ADMIN,
    AGENT = MEMBER_TYPE_ENUM.AGENT,
    APPRAISER = MEMBER_TYPE_ENUM.APPRAISER,
    ATTORNEY = MEMBER_TYPE_ENUM.ATTORNEY,
    BROKER = MEMBER_TYPE_ENUM.BROKER,
    BUYER = MEMBER_TYPE_ENUM.BUYER,
    CONTRACTOR = MEMBER_TYPE_ENUM.CONTRACTOR,
    FRIEND_FAMILY = MEMBER_TYPE_ENUM.FRIEND_FAMILY,
    INSPECTOR = MEMBER_TYPE_ENUM.INSPECTOR,
    LENDER = MEMBER_TYPE_ENUM.LENDER,
    RENTER = MEMBER_TYPE_ENUM.RENTER,
    SELLER = MEMBER_TYPE_ENUM.SELLER,
    TITLE_AGENT = MEMBER_TYPE_ENUM.TITLE_AGENT,
    TRANSACTION_COORDINATOR = MEMBER_TYPE_ENUM.TRANSACTION_COORDINATOR,
    OTHER = MEMBER_TYPE_ENUM.OTHER
  }
  
  export const MEMBER_TYPE = Object.values(MEMBER_TYPE_ENUM);